version: '3.7'

services:
  pri_solr:
    container_name: pri_solr
    build: solr
    ports:
      - "8983:8983"

  pri_web:
    build: frontend
    container_name: pri_web
    volumes:
      - ./frontend/code:/var/www/html
    ports:
      - 8000:80
