version: '3.7'

services:
  pri_solr:
    build: solr
    ports:
      - "8983:8983"

  pri_web:
    build: frontend
    container_name: pri_web
    volumes:
      - ./frontend/code/index.html:/var/www/html/index.html
      - ./frontend/code/eurlex/.htaccess:/var/www/html/eurlex/.htaccess
      - ./data/eurlex/texts:/var/www/html/eurlex/legal-content/EN/TXT/HTML
    ports:
      - 8000:80
